baseurl = "/"
title = "Jerome Brette's Blog"
languageCode = "en-us"
paginate = "20" # Number of posts per page
theme = "mainroad"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[Author]
  name = "Jerome Brette"
  bio = "Jerome Brette is a Principal Architect at Ericsson particularly interested in edge network ecosystems, machine learning, big data."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Raspberry PI are powerfull play and training ground" # Subtitle of your site
  description = " Jerome Brette's Personal blog about everything" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  leftsidebar = false # Move sidebar to the left side if true
  authorbox = true
  post_navigation = true
#  postSections = ["posts", "news"]

[Params.widgets]
  search = true # Enable "Search" widget
  recent_articles = true # Enable "Recent arcticles" widget
  recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

  # Enable "Social" widget, if any of "social_*" set a value
  # social_twitter = "jebrette"
  social_linkedin = "jerome-brette-109b8711"
  social_github = "jbrette"
  # social_email = "example@example.com"
