baseurl = "https://jbrette.github.io/"
title = "Jerome Brette's Blog"
googleAnalytics = "UA-123357787-1" # Enable Google Analytics by entering your tracking id

canonifyurls = true
disqusShortname = "" # Enable comments by entering your Disqus shortname
enableRobotsTXT = true
languageCode = "en-us"
paginate = 20 # Number of posts per page

pluralizeListTitles = false
preserveTaxonomyNames = true

layoutdir = "layouts"
contentdir = "content"
publishdir = "public"
theme = "hugo-future-imperfect"

[taxonomies]
  category = "categories"
  tag = "tags"

[Author]
  name = "Jerome Brette"
  bio = "Jerome Brette is a Principal Architect at Ericsson particularly interested in edge network ecosystems, machine learning, big data."
  avatar = "img/avatar.png"

[Params]
  subtitle = "Staying sharp by leveraging Raspberry PI as play and training grounds" # Subtitle of your site
  description = " Jerome Brette's Blog" # Description of your site
  opengraph = true
  twitter_cards = false
  readmore = true # Show "Read more" button in list if true
  leftsidebar = false # Move sidebar to the left side if true
  authorbox = true
  post_navigation = true

  navbarTitle          = "My Edge Network"
  viewMorePostLink     = "/post/"
  dynamicTitles        = true
  socialAppearAtBottom = true
  socialShare          = true
  socialShareGitHub    = true
  socialShareLinkedin  = true
  disable_highlight = false # set to true to disable Highlight
  highlightjsVersion = "9.11.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["json", "yaml", "css", "go", "bash"]
  highlightjsTheme = "github"

[Params.postAmount]
  sidebar = 10

[Params.widgets]
  search = true # Enable "Search" widget
  recent_articles = true # Enable "Recent arcticles" widget
  recent_articles_num = 5 # Set the number of articles in the "Recent articles" widget
  categories = true # Enable "Categories" widget
  tags = true # Enable "Tags" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)

  # Enable "Social" widget, if any of "social_*" set a value
  # social_twitter = "jebrette"
  social_linkedin = "jerome-brette-109b8711"
  social_github = "jbrette"

[[menu.main]]
  name = "Home"
  url = "/"
  identifier = "fa fa-home"
  weight = 1

[[menu.main]]
  name = "Blog"
  url = "/post/"
  identifier = "fa fa-newspaper-o"
  weight = 2

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 3
  identifier = "fa fa-sitemap"

[[menu.main]]
  name = "About me"
  url = "/about/"
  identifier = "fa fa-address-card"
  weight = 4
